# Generated by Django 4.1.3 on 2023-09-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=15)),
                ("make", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=20)),
                ("colour", models.CharField(max_length=20)),
                ("seats", models.IntegerField()),
                ("available_seats", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="vehicles",
            field=models.ManyToManyField(to="users.vehicle"),
        ),
    ]
