# Generated by Django 4.1.3 on 2023-09-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0002_driverprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=15)),
                ("brand", models.CharField(max_length=20)),
                ("make", models.CharField(max_length=20)),
                ("colour", models.CharField(max_length=20)),
                ("seats", models.IntegerField()),
                ("available_seats", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="vehicle",
            field=models.ManyToManyField(to="drivers.vehicle"),
        ),
    ]
